# Generated by Django 5.0.1 on 2024-02-25 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_rename_user_name_user_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
