# Generated by Django 5.0.1 on 2024-03-06 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_users_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_verified',
        ),
    ]
